// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WichtelGenerator.Core.Configuration;

namespace WichtelGenerator.Core.Migrations
{
    [DbContext(typeof(ConfigContext))]
    partial class ConfigContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.9");

            modelBuilder.Entity("WichtelGenerator.Core.Configuration.ConfigModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Absender")
                        .HasColumnType("TEXT");

                    b.Property<int>("FontSize")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MailNotificationEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("NotificationsEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Passwort")
                        .HasColumnType("TEXT");

                    b.Property<int>("Port")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ServerName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SslOn")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("ConfigModels");
                });

            modelBuilder.Entity("WichtelGenerator.Core.Configuration.MailAdressModel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("ConfigModelID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Mail")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ConfigModelID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("MailAdressModel");
                });

            modelBuilder.Entity("WichtelGenerator.Core.Models.BlackListModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("BlackListModel");
                });

            modelBuilder.Entity("WichtelGenerator.Core.Models.SecretSantaModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("BlackListModelID")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ChoiseID")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ConfigModelID")
                        .HasColumnType("INTEGER");

                    b.Property<string>("MailAdress")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("WhiteListModelID")
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("BlackListModelID");

                    b.HasIndex("ChoiseID");

                    b.HasIndex("ConfigModelID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.HasIndex("WhiteListModelID");

                    b.ToTable("SecretSantaModel");
                });

            modelBuilder.Entity("WichtelGenerator.Core.Models.WhiteListModel", b =>
                {
                    b.Property<Guid>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.HasKey("ID");

                    b.HasIndex("ID")
                        .IsUnique();

                    b.ToTable("WhiteListModel");
                });

            modelBuilder.Entity("WichtelGenerator.Core.Configuration.MailAdressModel", b =>
                {
                    b.HasOne("WichtelGenerator.Core.Configuration.ConfigModel", null)
                        .WithMany("EmpfaengerListe")
                        .HasForeignKey("ConfigModelID");
                });

            modelBuilder.Entity("WichtelGenerator.Core.Models.SecretSantaModel", b =>
                {
                    b.HasOne("WichtelGenerator.Core.Models.BlackListModel", "BlackListModel")
                        .WithMany("BlackList")
                        .HasForeignKey("BlackListModelID");

                    b.HasOne("WichtelGenerator.Core.Models.SecretSantaModel", "Choise")
                        .WithMany()
                        .HasForeignKey("ChoiseID");

                    b.HasOne("WichtelGenerator.Core.Configuration.ConfigModel", null)
                        .WithMany("SecretSantaModels")
                        .HasForeignKey("ConfigModelID");

                    b.HasOne("WichtelGenerator.Core.Models.WhiteListModel", "WhiteListModel")
                        .WithMany("WhitList")
                        .HasForeignKey("WhiteListModelID");

                    b.Navigation("BlackListModel");

                    b.Navigation("Choise");

                    b.Navigation("WhiteListModel");
                });

            modelBuilder.Entity("WichtelGenerator.Core.Configuration.ConfigModel", b =>
                {
                    b.Navigation("EmpfaengerListe");

                    b.Navigation("SecretSantaModels");
                });

            modelBuilder.Entity("WichtelGenerator.Core.Models.BlackListModel", b =>
                {
                    b.Navigation("BlackList");
                });

            modelBuilder.Entity("WichtelGenerator.Core.Models.WhiteListModel", b =>
                {
                    b.Navigation("WhitList");
                });
#pragma warning restore 612, 618
        }
    }
}
